### ISSUE TITLE
Gui trouble

### ISSUE THREAD

**Issue by bigptq** [cottiAC/zombidleBot#1]
Hi.
Thank you for this
I'm having problems getting this to work.Do I need to change the settings manually? I run the ahk script but the gui never shows up. I'm using windows 7.

**Comment by cottiAC** [comment]
Thanks for your feedback.
The GUI will show up on your second Monitor right now and expect the same resolution.
Yes, there is room for improvement ;)

I changed the GUI position to the first monitor in the new release 1.2
Maybe its a good idea to save the position, so everybody can decide where the GUI will show up.

Same for the main browser window. If the zombidle window is already open, it will be moved to the second monitor. I will remove it and think about a better solution.

**Comment by bigptq** [comment]
Thank you for the quick answer and update. 
I only use one monitor so that's why it wasn't showing. 
Could you add some details on the variables idletime, interval and abilitytimer? 
I still haven't managed to get everything working but having a clicker while being able to do something else is great.

**Comment by cottiAC** [comment]
I pushed a new release where your GUI and browser position will be saved on bot shutdown.

Details about settings:
- idletime: if your mouse is over a browser window, the bot is paused to avoid taking away focus. So you can still work with other windows. This is the time in seconds, the bot will idle. After the time the bot will continue to click because you are most likely not at the keyboard ;) default: 60000ms
- interval: duration in ms between automatic clicks. Default: 50ms (20 clicks per second)
- abilitytimer: Duration in ms between use of abilities (Sloth, ...). First activation will trigger Sloth only. Second one will trigger all skills. Default: 325s

All the mentioned variables moved to privatesettings.ini the the current release. So you dont have to change them with every new release.

Can you provide the status.log logfile? Maybe I can figure out, whats the problem.
